import { Article, Keyword, Competitor, CompetitorArticle, KeywordComparison } from '@/types'
import { subHours, subDays, formatISO } from 'date-fns'

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'NVIDIA anuncia nova linha de GPUs RTX 5000 com IA aprimorada',
    totalScore: 98,
    averageScore: 9.8,
    source: 'The Verge',
    publishedAt: formatISO(subHours(new Date(), 2)),
    country: 'EUA',
    continent: 'América do Norte',
    url: 'https://www.theverge.com',
    keywords: ['NVIDIA', 'GPU', 'RTX 5000', 'IA'],
  },
  {
    id: '2',
    title: 'Apple lança MacBook Pro com chip M4 e design revolucionário',
    totalScore: 95,
    averageScore: 9.5,
    source: 'Bloomberg',
    publishedAt: formatISO(subHours(new Date(), 8)),
    country: 'EUA',
    continent: 'América do Norte',
    url: 'https://www.bloomberg.com',
    keywords: ['Apple', 'MacBook Pro', 'M4', 'Design'],
  },
  {
    id: '3',
    title: 'Vazamento revela detalhes do novo Samsung Galaxy S25',
    totalScore: 92,
    averageScore: 9.2,
    source: 'Canaltech',
    publishedAt: formatISO(subDays(new Date(), 1)),
    country: 'Brasil',
    continent: 'América do Sul',
    url: 'https://canaltech.com.br',
    keywords: ['Samsung', 'Galaxy S25', 'Vazamento'],
  },
  {
    id: '4',
    title: 'Google I/O 2024: Todas as novidades de Android 15 e IA Gemini',
    totalScore: 89,
    averageScore: 8.9,
    source: 'Engadget',
    publishedAt: formatISO(subDays(new Date(), 3)),
    country: 'EUA',
    continent: 'América do Norte',
    url: 'https://www.engadget.com',
    keywords: ['Google I/O', 'Android 15', 'Gemini', 'IA'],
  },
  {
    id: '5',
    title: 'Como a regulamentação de IA na Europa pode impactar o Brasil',
    totalScore: 85,
    averageScore: 8.5,
    source: 'Folha de S.Paulo',
    publishedAt: formatISO(subDays(new Date(), 5)),
    country: 'Brasil',
    continent: 'América do Sul',
    url: 'https://www.folha.uol.com.br',
    keywords: ['IA', 'Regulamentação', 'Europa', 'Brasil'],
  },
  {
    id: '6',
    title: 'Cyberpunk 2077: Phantom Liberty atinge 5 milhões de cópias vendidas',
    totalScore: 82,
    averageScore: 8.2,
    source: 'IGN',
    publishedAt: formatISO(subDays(new Date(), 7)),
    country: 'EUA',
    continent: 'América do Norte',
    url: 'https://www.ign.com',
    keywords: ['Cyberpunk 2077', 'Phantom Liberty', 'Games'],
  },
  {
    id: '7',
    title: 'Startup brasileira de fintech recebe investimento de R$ 100 milhões',
    totalScore: 79,
    averageScore: 7.9,
    source: 'Exame',
    publishedAt: formatISO(subDays(new Date(), 10)),
    country: 'Brasil',
    continent: 'América do Sul',
    url: 'https://exame.com',
    keywords: ['Fintech', 'Investimento', 'Startup'],
  },
  {
    id: '8',
    title: 'Microsoft apresenta o novo Surface Laptop com chips ARM',
    totalScore: 93,
    averageScore: 9.3,
    source: 'Wired',
    publishedAt: formatISO(subHours(new Date(), 20)),
    country: 'EUA',
    continent: 'América do Norte',
    url: 'https://www.wired.com',
    keywords: ['Microsoft', 'Surface', 'ARM', 'Windows'],
  },
  {
    id: '9',
    title: 'Análise do PlayStation 5 Pro: vale a pena o upgrade?',
    totalScore: 91,
    averageScore: 9.1,
    source: 'IGN Brasil',
    publishedAt: formatISO(subDays(new Date(), 2)),
    country: 'Brasil',
    continent: 'América do Sul',
    url: 'https://br.ign.com',
    keywords: ['PlayStation 5 Pro', 'Sony', 'Games', 'Review'],
  },
  {
    id: '10',
    title: 'Intel lança nova geração de processadores Lunar Lake',
    totalScore: 88,
    averageScore: 8.8,
    source: 'AnandTech',
    publishedAt: formatISO(subDays(new Date(), 4)),
    country: 'EUA',
    continent: 'América do Norte',
    url: 'https://www.anandtech.com',
    keywords: ['Intel', 'Lunar Lake', 'CPU'],
  },
  {
    id: '11',
    title: 'A guerra dos streamings: qual serviço oferece o melhor custo-benefício?',
    totalScore: 84,
    averageScore: 8.4,
    source: 'UOL',
    publishedAt: formatISO(subDays(new Date(), 6)),
    country: 'Brasil',
    continent: 'América do Sul',
    url: 'https://www.uol.com.br',
    keywords: ['Streaming', 'Netflix', 'HBO Max', 'Disney+'],
  },
  {
    id: '12',
    title: 'Tesla anuncia novo Roadster com aceleração recorde',
    totalScore: 96,
    averageScore: 9.6,
    source: 'Electrek',
    publishedAt: formatISO(subHours(new Date(), 12)),
    country: 'EUA',
    continent: 'América do Norte',
    url: 'https://electrek.co',
    keywords: ['Tesla', 'Roadster', 'Carro Elétrico'],
  },
  {
    id: '13',
    title: 'Meta lança novo headset de realidade virtual Quest 4',
    totalScore: 90,
    averageScore: 9.0,
    source: 'UploadVR',
    publishedAt: formatISO(subDays(new Date(), 3)),
    country: 'EUA',
    continent: 'América do Norte',
    url: 'https://uploadvr.com',
    keywords: ['Meta', 'Quest 4', 'VR', 'Realidade Virtual'],
  },
  {
    id: '14',
    title: 'Pix automático: como vai funcionar a nova modalidade de pagamento',
    totalScore: 86,
    averageScore: 8.6,
    source: 'G1',
    publishedAt: formatISO(subDays(new Date(), 9)),
    country: 'Brasil',
    continent: 'América do Sul',
    url: 'https://g1.globo.com',
    keywords: ['Pix', 'Banco Central', 'Fintech'],
  },
  {
    id: '15',
    title: 'Elden Ring: Shadow of the Erdtree - Primeiras impressões da DLC',
    totalScore: 94,
    averageScore: 9.4,
    source: 'Eurogamer',
    publishedAt: formatISO(subDays(new Date(), 1)),
    country: 'Reino Unido',
    continent: 'Europa',
    url: 'https://www.eurogamer.net',
    keywords: ['Elden Ring', 'DLC', 'Games', 'FromSoftware'],
  },
  {
    id: '16',
    title: 'AMD revela arquitetura Zen 5 para processadores Ryzen 8000',
    totalScore: 92,
    averageScore: 9.2,
    source: 'PC Gamer',
    publishedAt: formatISO(subDays(new Date(), 5)),
    country: 'EUA',
    continent: 'América do Norte',
    url: 'https://www.pcgamer.com',
    keywords: ['AMD', 'Zen 5', 'Ryzen 8000', 'CPU'],
  },
  {
    id: '17',
    title: 'Criptomoedas em queda: o que esperar do mercado de Bitcoin e Ethereum',
    totalScore: 78,
    averageScore: 7.8,
    source: 'InfoMoney',
    publishedAt: formatISO(subDays(new Date(), 11)),
    country: 'Brasil',
    continent: 'América do Sul',
    url: 'https://www.infomoney.com.br',
    keywords: ['Criptomoedas', 'Bitcoin', 'Ethereum'],
  },
  {
    id: '18',
    title: 'Starlink de Elon Musk chega a áreas remotas da Amazônia',
    totalScore: 87,
    averageScore: 8.7,
    source: 'Reuters',
    publishedAt: formatISO(subDays(new Date(), 6)),
    country: 'Brasil',
    continent: 'América do Sul',
    url: 'https://www.reuters.com',
    keywords: ['Starlink', 'SpaceX', 'Internet', 'Amazônia'],
  },
  {
    id: '19',
    title: 'Novo drone da DJI promete filmagens em 8K e maior autonomia de voo',
    totalScore: 89,
    averageScore: 8.9,
    source: 'DPReview',
    publishedAt: formatISO(subDays(new Date(), 4)),
    country: 'EUA',
    continent: 'América do Norte',
    url: 'https://www.dpreview.com',
    keywords: ['DJI', 'Drone', '8K', 'Fotografia'],
  },
  {
    id: '20',
    title: 'A ascensão dos super apps na América Latina',
    totalScore: 83,
    averageScore: 8.3,
    source: 'TechCrunch',
    publishedAt: formatISO(subDays(new Date(), 15)),
    country: 'EUA',
    continent: 'América do Norte',
    url: 'https://techcrunch.com',
    keywords: ['Super Apps', 'América Latina', 'Startup'],
  },
]

export const MOCK_KEYWORDS: Keyword[] = [
  {
    id: 'k1',
    name: 'IA',
    overallScore: 99,
    quantityScore: 98,
    recencyScore: 99,
    relevanceScore: 97,
    trendScore: 99,
  },
  {
    id: 'k2',
    name: 'NVIDIA',
    overallScore: 97,
    quantityScore: 95,
    recencyScore: 98,
    relevanceScore: 96,
    trendScore: 98,
  },
  {
    id: 'k3',
    name: 'Apple',
    overallScore: 95,
    quantityScore: 94,
    recencyScore: 96,
    relevanceScore: 95,
    trendScore: 95,
  },
  {
    id: 'k4',
    name: 'Samsung',
    overallScore: 91,
    quantityScore: 92,
    recencyScore: 90,
    relevanceScore: 93,
    trendScore: 89,
  },
  {
    id: 'k5',
    name: 'Google',
    overallScore: 88,
    quantityScore: 87,
    recencyScore: 89,
    relevanceScore: 88,
    trendScore: 87,
  },
  {
    id: 'k6',
    name: 'Games',
    overallScore: 85,
    quantityScore: 86,
    recencyScore: 84,
    relevanceScore: 85,
    trendScore: 83,
  },
  {
    id: 'k7',
    name: 'Fintech',
    overallScore: 80,
    quantityScore: 78,
    recencyScore: 82,
    relevanceScore: 81,
    trendScore: 79,
  },
  {
    id: 'k8',
    name: 'Microsoft',
    overallScore: 92,
    quantityScore: 90,
    recencyScore: 93,
    relevanceScore: 91,
    trendScore: 94,
  },
  {
    id: 'k9',
    name: 'Sony',
    overallScore: 89,
    quantityScore: 88,
    recencyScore: 90,
    relevanceScore: 89,
    trendScore: 88,
  },
  {
    id: 'k10',
    name: 'Intel',
    overallScore: 86,
    quantityScore: 85,
    recencyScore: 87,
    relevanceScore: 86,
    trendScore: 85,
  },
  {
    id: 'k11',
    name: 'Streaming',
    overallScore: 83,
    quantityScore: 84,
    recencyScore: 82,
    relevanceScore: 83,
    trendScore: 81,
  },
  {
    id: 'k12',
    name: 'Tesla',
    overallScore: 96,
    quantityScore: 94,
    recencyScore: 97,
    relevanceScore: 95,
    trendScore: 97,
  },
  {
    id: 'k13',
    name: 'Realidade Virtual',
    overallScore: 87,
    quantityScore: 86,
    recencyScore: 88,
    relevanceScore: 87,
    trendScore: 86,
  },
  {
    id: 'k14',
    name: 'Pix',
    overallScore: 84,
    quantityScore: 82,
    recencyScore: 85,
    relevanceScore: 84,
    trendScore: 83,
  },
  {
    id: 'k15',
    name: 'Criptomoedas',
    overallScore: 77,
    quantityScore: 76,
    recencyScore: 78,
    relevanceScore: 77,
    trendScore: 75,
  },
  {
    id: 'k16',
    name: 'AMD',
    overallScore: 90,
    quantityScore: 89,
    recencyScore: 91,
    relevanceScore: 90,
    trendScore: 89,
  },
  {
    id: 'k17',
    name: 'Drone',
    overallScore: 82,
    quantityScore: 81,
    recencyScore: 83,
    relevanceScore: 82,
    trendScore: 80,
  },
  {
    id: 'k18',
    name: 'Startup',
    overallScore: 79,
    quantityScore: 80,
    recencyScore: 79,
    relevanceScore: 78,
    trendScore: 77,
  },
]

export const MOCK_COMPETITORS: Competitor[] = [
  {
    id: 'c1',
    name: 'Canaltech',
    avgKeywordPosition: 2.5,
    rankedKeywordsCount: 150,
  },
  {
    id: 'c2',
    name: 'The Verge',
    avgKeywordPosition: 3.1,
    rankedKeywordsCount: 120,
  },
  {
    id: 'c3',
    name: 'Engadget',
    avgKeywordPosition: 4.2,
    rankedKeywordsCount: 110,
  },
  {
    id: 'c4',
    name: 'Gizmodo Brasil',
    avgKeywordPosition: 5.0,
    rankedKeywordsCount: 95,
  },
  { id: 'c5', name: 'Wired', avgKeywordPosition: 5.2, rankedKeywordsCount: 92 },
  {
    id: 'c6',
    name: 'TechCrunch',
    avgKeywordPosition: 5.8,
    rankedKeywordsCount: 88,
  },
  {
    id: 'c7',
    name: 'IGN Brasil',
    avgKeywordPosition: 6.1,
    rankedKeywordsCount: 85,
  },
  {
    id: 'c8',
    name: 'UOL Tilt',
    avgKeywordPosition: 6.5,
    rankedKeywordsCount: 80,
  },
  {
    id: 'c9',
    name: 'G1 Tecnologia',
    avgKeywordPosition: 7.0,
    rankedKeywordsCount: 75,
  },
  {
    id: 'c10',
    name: 'PC Gamer',
    avgKeywordPosition: 7.3,
    rankedKeywordsCount: 72,
  },
  {
    id: 'c11',
    name: 'AnandTech',
    avgKeywordPosition: 7.8,
    rankedKeywordsCount: 68,
  },
  {
    id: 'c12',
    name: 'Ars Technica',
    avgKeywordPosition: 8.0,
    rankedKeywordsCount: 65,
  },
]

export const MOCK_COMPETITOR_ARTICLES: CompetitorArticle[] = [
  {
    competitorName: 'Canaltech',
    seoScore: 96,
    mainKeywords: ['iPhone 16', 'Review', 'Apple'],
    ...MOCK_ARTICLES[1],
  },
  {
    competitorName: 'The Verge',
    seoScore: 93,
    mainKeywords: ['Notebook Gamer', '2024', 'Review'],
    ...MOCK_ARTICLES[0],
  },
  {
    competitorName: 'Engadget',
    seoScore: 90,
    mainKeywords: ['Android 15', 'iOS 18', 'Comparativo'],
    ...MOCK_ARTICLES[3],
  },
  {
    competitorName: 'Gizmodo Brasil',
    seoScore: 95,
    mainKeywords: ['Samsung', 'Galaxy S25', 'Review'],
    ...MOCK_ARTICLES[2],
  },
  {
    competitorName: 'Wired',
    seoScore: 92,
    mainKeywords: ['IA', 'Gemini', 'Google'],
    ...MOCK_ARTICLES[3],
  },
  {
    competitorName: 'IGN Brasil',
    seoScore: 89,
    mainKeywords: ['Cyberpunk 2077', 'Phantom Liberty', 'Games'],
    ...MOCK_ARTICLES[5],
  },
  {
    competitorName: 'The Verge',
    seoScore: 94,
    mainKeywords: ['Microsoft', 'Surface', 'ARM'],
    ...MOCK_ARTICLES[7],
  },
  {
    competitorName: 'UOL Tilt',
    seoScore: 91,
    mainKeywords: ['PlayStation 5 Pro', 'Sony', 'Games'],
    ...MOCK_ARTICLES[8],
  },
  {
    competitorName: 'AnandTech',
    seoScore: 88,
    mainKeywords: ['Intel', 'Lunar Lake', 'CPU'],
    ...MOCK_ARTICLES[9],
  },
  {
    competitorName: 'Engadget',
    seoScore: 97,
    mainKeywords: ['Tesla', 'Roadster', 'Carro Elétrico'],
    ...MOCK_ARTICLES[11],
  },
  {
    competitorName: 'TechCrunch',
    seoScore: 90,
    mainKeywords: ['Meta', 'Quest 4', 'VR'],
    ...MOCK_ARTICLES[12],
  },
  {
    competitorName: 'PC Gamer',
    seoScore: 98,
    mainKeywords: ['Elden Ring', 'DLC', 'Games'],
    ...MOCK_ARTICLES[14],
  },
]

export const MOCK_KEYWORD_COMPARISON_STRONG: KeywordComparison[] = [
  { keyword: 'Hardware Brasil', tecmundoScore: 95, competitorScore: 70 },
  { keyword: 'Reviews de Smartphones', tecmundoScore: 92, competitorScore: 75 },
  { keyword: 'Notícias de Tecnologia', tecmundoScore: 90, competitorScore: 80 },
]

export const MOCK_KEYWORD_COMPARISON_WEAK: KeywordComparison[] = [
  { keyword: 'Cultura Pop', tecmundoScore: 65, competitorScore: 90 },
  { keyword: 'Streaming', tecmundoScore: 70, competitorScore: 88 },
  { keyword: 'Games Indie', tecmundoScore: 72, competitorScore: 85 },
]
