services:
  web:
    container_name: app-dev
    working_dir: /app
    build:
      context: ../
      dockerfile: docker/dev.Dockerfile
    env_file: ../.env
    volumes:
      - ../:/app
      - /app/node_modules
    restart: always
    ports:
      - 5000:5000
    networks:
      - local
  redis:
    container_name: redis-dev
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - local

networks:
  local: